name: testeador_example
description: Example Flutter app demonstrating testeador with Pokémon battles.
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  dio: ^5.0.0
  flutter:
    sdk: flutter
  testeador:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.30.0
  very_good_analysis: ^6.0.0

dependency_overrides:
  test: ^1.30.0
  test_api: 0.7.10
