// Raw strings keep template bodies safe to evolve: any future `${expr}`
// added to the snippet stays literal instead of being treated as Dart
// interpolation.
// ignore_for_file: unnecessary_raw_strings

/// Template for `test/contract_test.dart` — registers flows with `dart test`.
///
/// Placeholders:
///   {{flow_imports}}     Relative imports for flow files.
///   {{flows_list}}       Comma-separated flow-builder calls.
///   {{options_arg}}      Optional `TesteadorOptions(...)` literal or empty.
const contractTestTemplate = r'''
// Auto-generated by testeador_mcp scaffold_dart_test_main.
// Registers every flow with `package:test` so they run as `dart test` blocks.
//
// Run all:        dart test test/contract_test.dart
// Run by name:    dart test test/contract_test.dart -N <substring>
// Run by tag:     dart test test/contract_test.dart -t smoke

import 'package:testeador/testeador.dart';

{{flow_imports}}

void main() {
  Testeador(
    flows: [
      {{flows_list}}
    ],
  ).registerWithDartTest({{options_arg}});
}
''';
