// Raw strings keep template bodies safe to evolve: any future `${expr}`
// added to the snippet stays literal instead of being treated as Dart
// interpolation.
// ignore_for_file: unnecessary_raw_strings

/// Template for a `dart test` entrypoint that injects captured tests via
/// `TestInjector.<id>`.
///
/// Placeholders:
///   {{header_comment}}       Leading explanatory comment (multi-line OK).
///   {{consumer_package}}     Package that owns `lib/test_injector.g.dart`.
///   {{flow_function}}        Builder function name (e.g. `buildPickedFlow`).
///   {{flow_kind_class}}      `TestFlowLasting` or `TestFlowTransient`.
///   {{flow_name}}            Human-readable flow name (already escaped).
///   {{flow_description}}     Optional description (already escaped).
///   {{tags_literal}}         Full set literal — `{'smoke', 'e2e'}` or `{}`.
///   {{steps_block}}          `TestInjector.<id>,` entries, comma-separated.
const injectedFlowTemplate = r'''
// GENERATED by `testeador discover` — review before committing.
// Re-run `dart run build_runner build` if you edit the original `test()`
// names; the static `TestInjector.<id>` references below are codegen-derived
// and will break otherwise.
{{header_comment}}

import 'package:{{consumer_package}}/test_injector.g.dart';
import 'package:testeador/testeador.dart';

{{flow_kind_class}} {{flow_function}}() {
  return {{flow_kind_class}}(
    name: '{{flow_name}}',
    description: '{{flow_description}}',
    tags: {{tags_literal}},
    steps: [
      {{steps_block}}
    ],
  );
}

void main() {
  Testeador(flows: [{{flow_function}}()]).registerWithDartTest();
}
''';
