// Raw strings keep template bodies safe to evolve: any future `${expr}`
// added to the snippet stays literal instead of being treated as Dart
// interpolation.
// ignore_for_file: unnecessary_raw_strings

/// Template for `bin/run_tests.dart` — standalone CLI entrypoint.
///
/// Placeholders:
///   {{actor_imports}}    Relative imports for actor files.
///   {{flow_imports}}     Relative imports for flow files.
///   {{actor_block}}      Dart statements that instantiate actors.
///   {{actors_list}}      Comma-separated actor variable names.
///   {{flows_list}}       Comma-separated flow-builder calls.
const runTestsCliTemplate = r'''
// Auto-generated by testeador mcp scaffold_suite_runner.
// Aggregates every flow in the suite under a single CLI entrypoint.
//
// Smoke gate (CI):
//     dart compile exe bin/run_tests.dart -o test_runner
//     ./test_runner --include-tags smoke
//
// Full regression:
//     ./test_runner --include-tags regression
//
// Local dev (everything):
//     dart run bin/run_tests.dart

import 'package:testeador/testeador.dart';

{{actor_imports}}
{{flow_imports}}

Future<void> main(List<String> args) async {
  {{actor_block}}

  await Testeador(
    actors: [{{actors_list}}],
    flows: [
      {{flows_list}}
    ],
  ).run(args);
}
''';
